#################################################################
## Home Assistant
#################################################################
homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: imperial
  customize: !include customize.yaml
  time_zone: !secret homeassistant_timezone
  external_url: "https://ha.useroneREDACTED.com"
  internal_url: "http://REDACTED54:8123"
  allowlist_external_dirs:
    - /shared
    - /config
  allowlist_external_urls:
    - "https://ha.useroneREDACTED.com/api/frigate/notifications/"

api:
frontend:
  themes: !include_dir_merge_named themes
sun:
#ios:
map:
config:
discovery:
  ignore:
    - netgear_router
    - harmony
    - google_cast
    - philips_hue
    - yeelight
    - denonavr
#conversation: TESTING 123
logger: !include logger.yaml

logbook: !include logbook.yaml

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/lovelace-battery-entity/battery-entity.js
      type: module
    - url: /hacsfiles/simple-thermostat/simple-thermostat.js
      type: module
    - url: /hacsfiles/weather-card/weather-card.js
      type: module
    - url: /hacsfiles/text-divider-row/text-divider-row.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/air-visual-card/air-visual-card.js
      type: module
    - url: /hacsfiles/entity-attributes-card/entity-attributes-card.js?=v2
      type: module
    - url: /hacsfiles/threedy/threedy-card.js
      type: module

shell_command:
  docker_image_prune_docker1: "ssh -i /shared/id_rsa -oStrictHostKeyChecking=no vagrant@REDACTED54 'docker image prune -af'"
  docker_image_prune_docker2: "ssh -i /shared/id_rsa -oStrictHostKeyChecking=no vagrant@REDACTED53 'docker image prune -af'"
  docker_image_prune_docker3: "ssh -i /shared/id_rsa -oStrictHostKeyChecking=no vagrant@REDACTED 'docker image prune -af'"

system_health:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.18.0.0/24

#################################################################
## Components
#################################################################

alexa:
  smart_home:
    filter:
      include_entities:
        - switch.pentair_REDACTED_spa
        - light.pentair_REDACTED_lights
        - switch.pentair_REDACTED_spillway
        - sensor.pentair_REDACTED_pool_temperatur
        - switch.media_center_shield
        - switch.media_center_switch
        - switch.media_center_xbox
    entity_config:
      switch.pentair_REDACTED_spa:
        name: "Spa"
        description: "The spa"
      light.pentair_REDACTED_lights:
        name: "Pool light"
        description: "Pool light"
      switch.pentair_REDACTED_spillway:
        name: "Spillway"
        description: "Spillway"
      sensor.pentair_REDACTED_pool_temperature:
        name: "Pool"
        description: "Pool water temperature"
      switch.media_center_shield:
        name: "Shield"
        description: "Downstairs nvidia shield harmony activity"
      switch.media_center_switch:
        name: "Switch"
        description: "Downstairs nin switch harmony activity"
      switch.media_center_xbox:
        name: "Xbox"
        description: "Downstairs xbox harmony activity"

ffmpeg:

monitor_docker:
  - name: docker1
    url: tcp://REDACTED54:2375
  - name: docker2
    url: tcp://REDACTED53:2375
    containers:
      - unifi-controller
  - name: docker3
    url: tcp://REDACTED:2375
    containers:
      - homeassistant

rainbird:
  host: !secret rainbird_host
  password: !secret rainbird_password
  trigger_time: 60

ring:
  username: !secret ring_username
  password: !secret ring_password

tts:
  - platform: google_translate
    cache: true
    time_memory: 300
    base_url: http://REDACTED:8123
    
sonos:
  media_player:
    hosts:
      - REDACTED
      - REDACTED
      - REDACTED
      - REDACTED

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: daily

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_key

yeelight:
  devices:
    !secret media_center_l_strip_host:
      name: Media Center L Strip
      model: strip1
    !secret media_center_r_strip_host:
      name: Media Center R Strip
      model: strip1

#################################################################
## Includes
#################################################################

automation: !include_dir_merge_list automation
binary_sensor: !include binary_sensor.yaml
group: !include groups.yaml
history: !include history.yaml
input_boolean: !include input_boolean.yaml
input_button: !include input_button.yaml
input_datetime: !include input_datetime.yaml
input_select: !include input_select.yaml
light: !include light.yaml
recorder: !include recorder.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
switch: !include switch.yaml
zone: !include zones.yaml
